table dim_sku
	lineageTag: 359ba7ff-d6f7-4e05-94c9-677c863c3ba2

	column SKU
		dataType: int64
		formatString: 0
		lineageTag: 98717948-7395-4a6e-9e43-fc786f484e55
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column 'Ngành hàng'
		dataType: string
		lineageTag: dacbf4ce-3312-4d87-a1d4-5908bf40d349
		summarizeBy: none
		sourceColumn: Ngành hàng
		sortByColumn: 'Mã Ngành hàng'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Nhóm hàng'
		dataType: string
		lineageTag: 1f8ba0f9-f25d-4c9d-8041-669abe4c21ce
		summarizeBy: none
		sourceColumn: Nhóm hàng

		annotation SummarizationSetBy = Automatic

	column 'Mã Ngành hàng'
		dataType: string
		lineageTag: 5cb55a8e-f810-46e4-965d-1b43f70535e8
		summarizeBy: none
		sourceColumn: Mã Ngành hàng

		annotation SummarizationSetBy = Automatic

	partition dim_sku = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\phamt\OneDrive\Documents\GitHub\sales-performance-powerbi\data\sku.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SKU", Int64.Type}, {"Ngành hàng", type text}, {"Nhóm hàng", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","MAY MẶC","MM",Replacer.ReplaceText,{"Ngành hàng"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","GIA DỤNG","ĐD",Replacer.ReplaceText,{"Ngành hàng"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value1", "Custom", each if [Ngành hàng] = "TPTS" then 1 else if [Ngành hàng] = "TPCN" then 2 else if [Ngành hàng] = "HMP" then 3 else if [Ngành hàng] = "ĐD" then 4 else if [Ngành hàng] = "MM" then 5 else null),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Mã Ngành hàng"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

